INSERT INTO region VALUES (1, 'DLN_WROC_C', 'Dolnośląskie - Wrocław centrum');
INSERT INTO region VALUES (2, 'DLN_WROC_PC', 'Dolnośląskie - Wrocław poza centrum');
INSERT INTO region VALUES (3, 'DLN_POZA_WROC', 'Dolnośląskie - poza Wrocławiem');
INSERT INTO region VALUES (4, 'SL_POL', 'Śląskie - południe');
INSERT INTO region VALUES (5, 'SL_KATO', 'Śląskie - Katowice');
INSERT INTO region VALUES (6, 'SL_PN', 'Śląskie - północ');
INSERT INTO region VALUES (7, 'M_WAW_CE', 'Mazowieckie - Warszawa Centrum');
INSERT INTO region VALUES (8, 'M_WAW_W', 'Mazowieckie - Warszawa wschód');
INSERT INTO region VALUES (9, 'M_WAW_Z', 'Mazowieckie - Warszaawa - zachód');
INSERT INTO region VALUES (10, 'LUBL', 'Lubelskie - Lublin');
INSERT INTO region VALUES (11, 'LUBL_INNE', 'Lubelskie - poza Lublinem');
INSERT INTO region VALUES (12, 'ZPOM', 'Zachodniopomorskie');
INSERT INTO region VALUES (13, 'LUBSK', 'Lubuskie');
